language: java
script: ant package
deploy:
   edge: true
   provider: cloudfoundry
   username: vignesh.nagarajan@verizon.com
   password: sivakasi
   api: https://api.run.pivotal.io
   organization: phoneixvzn
   space: development
